config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'welcome/index'

  resources :articles
  resources :milestones
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/milestone.rb
class Milestone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :text))
    @article.save
    redirect_to @article
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  # このサーバーに以下のようなリクエストが来たときにレスポンスするコントローラー
  # GET /milestones HTTP/1.1
  # GETとかの意味はここ
  # http://www.tohoho-web.com/ex/http.htm
  # https://ja.wikipedia.org/wiki/Hypertext_Transfer_Protocol

  # GET /milestones.format
  def index
    #　Milestoneモデルをすべて取得
    @milestones = Milestone.all
    # URLの拡張子によって出力を切り替える
    respond_to do |format|
      # formatが空のときはhtmlとされる
      # /views/milestones/index.html.erb
      format.html
      # 拡張子がjsonだったら、jsonフォーマットで出力
      # http://www.tohoho-web.com/ex/json.html
      #　https://ja.wikipedia.org/wiki/JavaScript_Object_Notation
      format.json { render :json => @milestones}
      format.xml { render :xml => @milestones}
    end
  end
  
  # GET /milestones/new
  def new
    # 空のMilestoneモデルを生成
    @milestone = Milestone.new
    # /views/milestones/new.html.erb
  end
  
  #　POST　/milestones
  def create
    #　paramsの中の値でMilestoneモデルを生成
    # require =　必要　milestoneが必須
    #　permit ＝　許す　name,distance,photo_urlを許可
    @milestone = Milestone.new(params.require(:milestone).permit(:name, :distance, :photo_url))
    # Milestoneモデルを保存
    @milestone.save
    # redirect 向け直す　
    #　/milestones/@milestone.id
    redirect_to @milestone
  end

  # GET /milestones/:id
  def show
    #　Milestoneモデルのidを取得
    @milestone = Milestone.find(params[:id])
    # /views/milestones/show.html.erb
  end

  # GET /milestones/:id/edit 
  def edit
    #　Milestoneモデルのidを取得
    @milestone = Milestone.find(params[:id])
    # /views/milestones/edit.html.erb
  end

  # PATCH /milestones/:id
  def update
    #　Milestoneモデルのidを取得
    @milestone = Milestone.find(params[:id])
    #　permit ＝　許す　name,distance,photo_urlを許可
    #  既存のMilestoneモデルを上書き
    @milestone.update(params.require(:milestone).permit(:name, :distance, :photo_url))
    # /milestones
    redirect_to milestones_path
  end

  # DELETE /milestones/:id
  def destroy
    #　Milestoneモデルのidを取得
    @milestone = Milestone.find(params[:id])
    #  既存のMilestoneモデルを消去
    @milestone.destroy
    # /milestones
    redirect_to milestones_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/milestone_helper.rb
module MilestoneHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<%= link_to 'Articles', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Senro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/milestones/_form.html.erb
<!-- form_with で　htmlフォームを生成 -->
<%= form_with model: @milestone, local: true do |form| %>
  <p>
    <!-- <label for="milestone_name">Name</label> -->
    <%= form.label :name %>
    <br>
    <!-- <input type="text" name="milestone[name]" id="milestone_name"> -->
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :distance %><br>
    <%= form.text_field :distance %>
  </p>
  <p>
    <%= form.label :photo_url %><br>
    <%= form.text_field :photo_url %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/milestones/edit.html.erb
<h1>Edit milestone</h1>

<%= render "form" %>

<%= link_to "戻る", milestones_path %>

app/views/milestones/index.html.erb
<h1>Listing milestones</h1>
<!-- comment -->
<!-- <%= %> の中はrubyスクリプトとして評価される -->
<!-- link_to 文字列　url という記法でリンクを生成　-->
<%= link_to 'New milestone', new_milestone_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Distance</th>
    <th>Photo_url</th>
    <th></th>
    <th></th>
  </tr>
  <!-- milestones の中にはMilestonesモデルがすべてはいっている -->
  <!-- each =　それぞれに -->
  <!-- do からendまで繰り返す -->
  <% @milestones.each do |milestone| %>
    <tr>
      <td><%= milestone.name %></td>
      <td><%= milestone.distance %></td>
      <td><img src=<%= milestone.photo_url %> /></td>
      <td><%= link_to 'Show', milestone_path(milestone) %></td>
      <td><%= link_to 'Edit', edit_milestone_path(milestone) %></td>
      <td><%= link_to "Delete", milestone_path(milestone.id), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/milestones/new.html.erb
<h1>New milestone</h1>
<!-- render　文字列で　_文字列.html.erb　を取り込む -->
<%= render "form" %>

<%= link_to "戻る", milestones_path %>

app/views/milestones/show.html.erb
<p>
  <strong>name:</strong>
  <%= @milestone.name %>
</p>
<p>
  <strong>distance:</strong>
  <%= @milestone.distance %>
<p>
<p>
  <strong>photo_url:</strong>
  <%= @milestone.photo_url %>
</p>
   <%= link_to 'Milestone', milestones_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<h2>Hello, Hoge!</h2>
<p>Find me in app/views/welcome/index.html.erb</p>